### ISSUE TITLE
Batch Import hangs while importing the PHB (Chapter 3: Classes)

### ISSUE THREAD

**Issue by King-Wedgie** [VTTAssets/vtta-ddb#25]
**Affected Module:** VTTA D&D Beyond Integration v2.0.4: Up-to-date

*Running on a brand new world in FVTT 0.8.8, DnD5e 1.3.6, with only the VTTA modules enabled (core 2.0.1, integration 2.0.4, tokens 2.0.3; using extension 2.0.2)*

1) Log into Foundry VTT through Chrome, then log into a world and enable the VTTA Core and DDB Integration modules (Tokens module optional)
2) Ensure that the VTTA DDB Extension is connected to Foundry.
3) Log in to DnDBeyond on Chrome. Navigate to and attempt to import the Player's Handbook. 

Batch Import will run through the preface and chapters 1 and 2 just fine, but hangs indefinitely on chapter 3. (As a note, I've been able to install the MM and DMG with no issues, along with the DoIP adventure and MOoT campaign sourcebook for good measure).

*It also appears that the Patreon-only Bug Reporter is not working for me as well, which is what I initially tried to report through*

**Comment by King-Wedgie** [comment]
Meant to add that I've seen several others mention this issue in the Discord and on Patreon, but didn't see a formal report for it anywhere yet.

**Comment by VTTAssets** [comment]
I can confirm that it stops at that section and I am investigating why there is no response at all from the parser. Right now I am assuming a misconfiguration and a request body that is too large. Thanks for bringing it to my attention by submitting an issue here, that's probably easier from now on.

**Comment by VTTAssets** [comment]
My feeling was correct. Adjusting the max body size in the kubernetes ingress now allows larger content blobs to actually get into the parser. I tested it on the staging environment successfully and adjusted the production cluster now, too. Please re-open this issue if you still have problems importing the PHB, thanks!
