### ISSUE TITLE
[BATCH IMPORT] Xanathar's Guide to Everything

### ISSUE THREAD

**Issue by zag1024** [VTTAssets/vtta-ddb#28]
Import does not complete. Batch import of Xanathar's Guide to Everything stalls while importing monsters.

Issue:
Import attempts to access [https://www.dndbeyond.com/monsters/succubus-incubus](https://www.dndbeyond.com/monsters/succubus-incubus), which returns a 404 error.

**Comment by VTTAssets** [comment]
Thank you for reporting this issue. It is based on a wrong link found on the corresponding XGtE page: https://www.dndbeyond.com/sources/xgte/random-encounters

I will correct this error and replace it by two links to succubus and incubus in the next sources parser version.

**Comment by VTTAssets** [comment]
Issue resolved in the last parser update
