### ISSUE TITLE
Import of unprocessed modules seems to be available

### ISSUE THREAD

**Issue by VTTAssets** [VTTAssets/vtta-ddb#7]
**Reported by:** @Alamaise on [VTTA.io Discord](https://discord.com/channels/820602114740060191/820606902550659072/822917828096032778)
  
  I tried to batch import tomb of annihilation and nothing happens.
Importing a Kobold worked fine.

**Comment by VTTAssets** [comment]
Response is correct as 
```
{ 
  message: "Not (yet) supported"
  success: false
}
```

but the display fails to interpret that as a fault.

**Comment by VTTAssets** [comment]
Duplicated by #8

**Comment by AgentSells** [comment]
getting same for Dragon of Ice Spire Peak

**Comment by VTTAssets** [comment]
See https://github.com/VTTAssets/vtta.io/projects/2 for a status of each module. Link is available on discord by using the bot command `!status`, too.

**Comment by VTTAssets** [comment]
Resolved in Chrome extension 1.0.4
