### ISSUE TITLE
Importing Hoard of the Dragon Queen

### ISSUE THREAD

**Issue by ignatiuss** [VTTAssets/vtta-ddb#8]
I am trying to import Hoard of the dragon queen. I can see this message in Chrome Dev Tools:

{ 
  message: "Not (yet) supported"
  success: false
}

![vtta-dndbeyond-error-import-hotdq](https://user-images.githubusercontent.com/232595/111886140-f6f7e000-89c3-11eb-981e-dde8bd4421b3.png)

**Comment by VTTAssets** [comment]
Duplicate of #7
